name: Build the PR

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: use python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12' 
        
        - name: Install Dependencies
          run:  pip install --no-cache-dir -r requirements.txt

        - name: Run Build
          run: pylint --const-rgx='[a-z\_][a-z0-9\_]{2, 30}$' main.py
        
